# -*- coding: utf-8 -*-
"""classification_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoSiZLdb2cNC-09xelsh1344-mILQfQ7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay, confusion_matrix, roc_curve, roc_auc_score, RocCurveDisplay, log_loss

"""## Cargar dataset"""

df = pd.read_csv('Penguin_Species_Prediction_Dataset.csv')
print(df)
print(df.info())

"""## Identificar datos nulos"""

# Identificar datos nulos
print(df.isnull().sum ())

# Visualizar filas con datos nulos
df_null = df[df.isnull().any(axis=1)]

print(df_null.shape)

"""## Descriptive stats"""

# Exploracion de datos

# Crear dataframes para cada especie
df_adelie = df[df['species'] == 'Adelie']
df_chinstrap = df[df['species'] == 'Chinstrap']
df_gentoo = df[df['species'] == 'Gentoo']

# Crear dataframes para dividir por sexo

# Adelie
df_adelie_f = df_adelie[df_adelie['sex'] == 'Female']
df_adelie_m = df_adelie[df_adelie['sex'] == 'Male']

# Chinstrap
df_chinstrap_f = df_chinstrap[df_chinstrap['sex'] == 'Female']
df_chinstrap_m = df_chinstrap[df_chinstrap['sex'] == 'Male']

# Gentoo
df_gentoo_f = df_gentoo[df_gentoo['sex'] == 'Female']
df_gentoo_m = df_gentoo[df_gentoo['sex'] == 'Male']

"""### Histogramas por especie"""

# Plotear histogramas por cada especie, dividiendo por sexo

# Colores para los histogramas

# Female
colors_adelie_f = ["#CF7FB3", "#ECC4ED", "#64315E", "#BC9FC3"]
colors_chinstrap_f = ["#768B68", "#BEE0AE", "#526431", "#A0C39F"]
colors_gentoo_f = ["#9F7AAA", "#D7AEE0", "#572365", "#B79FD6"]

# Male
colors_adelie_m = ["#8B687F", "#AED9E0", "#315064", "#9FA0C3"]
colors_chinstrap_m = ["#B88A69", "#E0CBAE", "#645131", "#C3AC9F"]
colors_gentoo_m = ["#8B6868", "#E0AEAE", "#643131", "#C39F9F"]

# Histogramas

# Adelie - Male
axes_adelie_m = df_adelie_m[["culmen_length_mm", "culmen_depth_mm", "flipper_length_mm", "body_mass_g"]].hist(
    bins=20, grid=False, figsize=(10, 8), layout=(2, 2), edgecolor="black"
)
for ax, color in zip(axes_adelie_m.flatten(), colors_adelie_m):
    for patch in ax.patches:
        patch.set_facecolor(color)


plt.suptitle("Adelie - Male",
             fontsize=22, fontweight="regular")
plt.tight_layout()
plt.show()

# Adelie - Female
axes_adelie_f = df_adelie_f[["culmen_length_mm", "culmen_depth_mm", "flipper_length_mm", "body_mass_g"]].hist(
    bins=20, grid=False, figsize=(10, 8), layout=(2, 2), edgecolor="black"
)
for ax, color in zip(axes_adelie_f.flatten(), colors_adelie_f):
    for patch in ax.patches:
        patch.set_facecolor(color)


plt.suptitle("Adelie - Female",
             fontsize=22, fontweight="regular")
plt.tight_layout()
plt.show()

# Chinstrap - Male
axes_chinstrap_m = df_chinstrap_m[["culmen_length_mm", "culmen_depth_mm", "flipper_length_mm", "body_mass_g"]].hist(
    bins=20, grid=False, figsize=(10, 8), layout=(2, 2), edgecolor="black"
)
for ax, color in zip(axes_chinstrap_m.flatten(), colors_chinstrap_m):
    for patch in ax.patches:
        patch.set_facecolor(color)


plt.suptitle("Chinstrap - Male",
             fontsize=22, fontweight="regular")
plt.tight_layout()
plt.show()

# Chinstrap - Female
axes_chinstrap_f = df_chinstrap_f[["culmen_length_mm", "culmen_depth_mm", "flipper_length_mm", "body_mass_g"]].hist(
    bins=20, grid=False, figsize=(10, 8), layout=(2, 2), edgecolor="black"
)
for ax, color in zip(axes_chinstrap_f.flatten(), colors_chinstrap_f):
    for patch in ax.patches:
        patch.set_facecolor(color)


plt.suptitle("Chinstrap - Female",
             fontsize=22, fontweight="regular")
plt.tight_layout()
plt.show()

# Gentoo - Male
axes_gentoo_m = df_gentoo_m[["culmen_length_mm", "culmen_depth_mm", "flipper_length_mm", "body_mass_g"]].hist(
    bins=20, grid=False, figsize=(10, 8), layout=(2, 2), edgecolor="black"
)
for ax, color in zip(axes_gentoo_m.flatten(), colors_gentoo_m):
    for patch in ax.patches:
        patch.set_facecolor(color)


plt.suptitle("Gentoo - Male",
             fontsize=22, fontweight="regular")
plt.tight_layout()
plt.show()

# Gentoo - Female
axes_gentoo_f = df_gentoo_f[["culmen_length_mm", "culmen_depth_mm", "flipper_length_mm", "body_mass_g"]].hist(
    bins=20, grid=False, figsize=(10, 8), layout=(2, 2), edgecolor="black"
)
for ax, color in zip(axes_gentoo_f.flatten(), colors_gentoo_f):
    for patch in ax.patches:
        patch.set_facecolor(color)


plt.suptitle("Gentoo - Female",
             fontsize=22, fontweight="regular")
plt.tight_layout()
plt.show()

"""### Imputar nulos"""

# Imputar valores faltantes

# Variables numericas

# Guardar la mediana de cada variable por especie

# Adelie
median_cl_adelie = df_adelie['culmen_length_mm'].median()
median_cd_adelie = df_adelie['culmen_depth_mm'].median()
median_fl_adelie = df_adelie['flipper_length_mm'].median()
median_bm_adelie = df_adelie['body_mass_g'].median()

# Chinstrap
median_cl_chinstrap = df_chinstrap['culmen_length_mm'].median()
median_cd_chinstrap = df_chinstrap['culmen_depth_mm'].median()
median_fl_chinstrap = df_chinstrap['flipper_length_mm'].median()
median_bm_chinstrap = df_chinstrap['body_mass_g'].median()

# Gentoo
median_cl_gentoo = df_gentoo['culmen_length_mm'].median()
median_cd_gentoo = df_gentoo['culmen_depth_mm'].median()
median_fl_gentoo = df_gentoo['flipper_length_mm'].median()
median_bm_gentoo = df_gentoo['body_mass_g'].median()



# Adelie
df.loc[(df['species'] == 'Adelie') & (df['culmen_length_mm'].isna()),
       'culmen_length_mm'] = df['culmen_length_mm'].fillna(median_cl_adelie)

df.loc[(df['species'] == 'Adelie') & (df['culmen_depth_mm'].isna()),
       'culmen_depth_mm'] = df['culmen_depth_mm'].fillna(median_cd_adelie)

df.loc[(df['species'] == 'Adelie') & (df['flipper_length_mm'].isna()),
       'flipper_length_mm'] = df['flipper_length_mm'].fillna(median_fl_adelie)

df.loc[(df['species'] == 'Adelie') & (df['body_mass_g'].isna()),
       'body_mass_g'] = df['body_mass_g'].fillna(median_bm_adelie)


# Chinstrap
df.loc[(df['species'] == 'Chinstrap') & (df['culmen_length_mm'].isna()),
       'culmen_length_mm'] = df['culmen_length_mm'].fillna(median_cl_chinstrap)

df.loc[(df['species'] == 'Chinstrap') & (df['culmen_depth_mm'].isna()),
       'culmen_depth_mm'] = df['culmen_depth_mm'].fillna(median_cd_chinstrap)

df.loc[(df['species'] == 'Chinstrap') & (df['flipper_length_mm'].isna()),
       'flipper_length_mm'] = df['flipper_length_mm'].fillna(median_fl_chinstrap)

df.loc[(df['species'] == 'Chinstrap') & (df['body_mass_g'].isna()),
       'body_mass_g'] = df['body_mass_g'].fillna(median_bm_chinstrap)


# Gentoo
df.loc[(df['species'] == 'Gentoo') & (df['culmen_length_mm'].isna()),
       'culmen_length_mm'] = df['culmen_length_mm'].fillna(median_cl_gentoo)

df.loc[(df['species'] == 'Gentoo') & (df['culmen_depth_mm'].isna()),
       'culmen_depth_mm'] = df['culmen_depth_mm'].fillna(median_cd_gentoo)

df.loc[(df['species'] == 'Gentoo') & (df['flipper_length_mm'].isna()),
       'flipper_length_mm'] = df['flipper_length_mm'].fillna(median_fl_gentoo)

df.loc[(df['species'] == 'Gentoo') & (df['body_mass_g'].isna()),
       'body_mass_g'] = df['body_mass_g'].fillna(median_bm_gentoo)

# Imputar valores nulos de sex por 'Unknown'
df['sex'] = df['sex'].fillna('Unknown')

"""## Identificar duplicados"""

# Identificar si hay columnas duplicadas
print(df[df.duplicated() == True].sum())

"""## One hot encoding"""

# Inicializar one-hot encoder
encoder = OneHotEncoder(sparse_output=False)
encoder.set_output(transform="pandas")

# Encodear variables categoricas
encoded_features_df = encoder.fit_transform(df[['island','sex']])

# Juntar dataframe original con el dataframe con las variables encodeadas
df = df.join(encoded_features_df)

# Eliminar columna original de island
df.drop(columns=['island','sex'], inplace=True)

"""## Shuffle dataset"""

df = df.sample(frac=1, ignore_index=True, random_state=42)

"""### Separar dataset en df_x y df_y"""

# Features
df_x = df.drop(columns='species')

# Categories
df_y = df['species']

# Inicializar label encoder
label_encoder = LabelEncoder()

df_y_encoded = label_encoder.fit_transform(df_y)

# Separar los datos en train y test

# Primer split: 70% train, 30% temporal (que luego se divide en val y test)
df_x_train, df_x_temp, df_y_train, df_y_temp = train_test_split(
    df_x, df_y_encoded,
    test_size=0.3,
    random_state=42
)

# Segundo split: dividir el 30% temporal en 15% val y 15% test
df_x_val, df_x_test, df_y_val, df_y_test = train_test_split(
    df_x_temp, df_y_temp,
    test_size=0.5,
    random_state=42
)

# Verificación de tamaños
print("Train:", df_x_train.shape, "-",
      len(df_x_train)/len(df_x)*100, "%")
print("Val:  ", df_x_val.shape, "-", len(df_x_val)/len(df_x)*100, "%")
print("Test: ", df_x_test.shape, "-", len(df_x_test)/len(df_x)*100, "%")

# Estandarizar los datos despues de hacer los splits para evitar filtrado de datos
scaler = StandardScaler()

df_x_train = scaler.fit_transform(df_x_train)
df_x_val = scaler.transform(df_x_val)
df_x_test = scaler.transform(df_x_test)

# Inicializar el modelo
model = LogisticRegression(max_iter=1000)

# Entrenar el modelo
model.fit(df_x_train, df_y_train)

# Train

# Realizar predicciones
predictions_train = model.predict(df_x_train)

cm_train = confusion_matrix(df_y_train, predictions_train)

accuracy_train = accuracy_score(df_y_train, predictions_train)

loss_train = log_loss(df_y_train, model.predict_proba(df_x_train))

print("\n=======================TRAIN=======================\n")

print(cm_train)
print("Accuracy:", accuracy_train)
print("Error:", loss_train)

print(classification_report(df_y_train, predictions_train))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_train, display_labels=['Class 0', 'Class 1', 'Class 2'])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix - Train")
plt.show()

# Validation

# Realizar predicciones
predictions_val = model.predict(df_x_val)

cm_val = confusion_matrix(df_y_val, predictions_val)

accuracy_val = accuracy_score(df_y_val, predictions_val)

loss_val = log_loss(df_y_val,   model.predict_proba(df_x_val))

print("\n=======================VALIDATION=======================\n")

print(cm_val)
print("Accuracy:", accuracy_val)
print("Error:", loss_val)

print(classification_report(df_y_val, predictions_val))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_val, display_labels=['Class 0', 'Class 1', 'Class 2'])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix - Validation")
plt.show()



# Test

# Realizar predicciones
predictions_test = model.predict(df_x_test)

cm_test = confusion_matrix(df_y_test, predictions_test)

accuracy_test = accuracy_score(df_y_test, predictions_test)

loss_test = log_loss(df_y_test,  model.predict_proba(df_x_test))

print("\n=======================TEST=======================\n")

print(cm_test)
print("Accuracy:", accuracy_test)
print("Error:", loss_test)

print(classification_report(df_y_test, predictions_test))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_test, display_labels=['Class 0', 'Class 1', 'Class 2'])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix - Test")
plt.show()